name: Full AWS Security & Optimization Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  security_and_optimization:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read
      security-events: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::469440861178:role/GitHubActionsRole  # Updated IAM Role ARN
          aws-region: us-east-1

      # 1  tfsec - Terraform Security Scan Before Deployment
      - name: Run tfsec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: .
          soft_fail: false  # Set to true if you don't want it to block deployments

      # 2. AWS Well-Architected Tool - Check AWS Security & Best Practices
      - name: AWS Well-Architected Review Findings
        run: |
          WORKLOAD_ID="2a76e2c1bdbd5cba2df2088161181b62"  # Updated Workload ID

          echo "Fetching AWS Well-Architected Lenses..."
          aws wellarchitected list-lenses --region us-east-1 | jq
          
          echo "Fetching Workload Risk Summary..."
          aws wellarchitected get-workload --workload-id $WORKLOAD_ID --region us-east-1 | jq
          
          echo "Listing AWS Improvement Recommendations..."
          aws wellarchitected list-lens-review-improvements --workload-id $WORKLOAD_ID --lens-alias "wellarchitected" --region us-east-1 | jq

      # 3. AWS Trusted Advisor - Cost Optimization & Security Checks
      - name: AWS Trusted Advisor Security & Cost Report
        run: |
          aws support describe-trusted-advisor-checks --region us-east-1 | jq

      # 4. GitHub CodeQL - Scan Terraform & Other Code for Vulnerabilities
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: terraform  # Add more if needed (e.g., python, javascript)

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3