name: GitHub Actions Setup

on: [push, pull_request]  # Runs on every push or PR

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Confirm GitHub Actions is Working
        run: echo "GitHub Actions is successfully set up!"
